### ISSUE TITLE
Application crashing on Android 7 in release mode

### ISSUE THREAD

**Issue by giordanocardillo** [NathanWalker/nativescript-loading-indicator#42]
If I set up a view and just put there the library requiring line (just that, without even using it)
```js
var LoadingIndicator = require("nativescript-loading-indicator").LoadingIndicator;
```

The app crashes when running in release mode with package signature.

I made this test on android 7.1.2 on OnePlus One running Lineage OS.

Running without --release and signing goes just fine.

This is that I get 
```
09-25 16:49:42.937  3722  3722 W System.err:    at com.tns.Runtime.callJSMethodNative(Native Method)
09-25 16:49:42.937  3722  3722 W System.err:    at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1084)
09-25 16:49:42.937  3722  3722 W System.err:    at com.tns.Runtime.callJSMethodImpl(Runtime.java:966)
09-25 16:49:42.937  3722  3722 W System.err:    at com.tns.Runtime.callJSMethod(Runtime.java:953)
09-25 16:49:42.937  3722  3722 W System.err:    at com.tns.Runtime.callJSMethod(Runtime.java:937)
09-25 16:49:42.938  3722  3722 W System.err:    at com.tns.Runtime.callJSMethod(Runtime.java:929)
09-25 16:49:42.941  3722  3722 E AndroidRuntime:        at com.tns.Runtime.callJSMethodNative(Native Method)
09-25 16:49:42.941  3722  3722 E AndroidRuntime:        at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1084)
09-25 16:49:42.941  3722  3722 E AndroidRuntime:        at com.tns.Runtime.callJSMethodImpl(Runtime.java:966)
09-25 16:49:42.941  3722  3722 E AndroidRuntime:        at com.tns.Runtime.callJSMethod(Runtime.java:953)
09-25 16:49:42.941  3722  3722 E AndroidRuntime:        at com.tns.Runtime.callJSMethod(Runtime.java:937)
09-25 16:49:42.941  3722  3722 E AndroidRuntime:        at com.tns.Runtime.callJSMethod(Runtime.java:929)
```

I'm using {N} v3.0.3

**Comment by giordanocardillo** [comment]
I currently solved this using plugin version 2.2.2
