### ISSUE TITLE
Error when calling Hide

### ISSUE THREAD

**Issue by anaszgh** [NathanWalker/nativescript-loading-indicator#68]
Platform: Android
Runtime: 5.4.0
TNS Version: 5.4

I'm trying to hide the loading indicator using `loading.hide();`

the indicator disappears successfully but after almost 1 second the app crashes and the following message is logged.

`Calling js method onDismissed failed`

here is the stack trace 

```
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1203)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1083)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1070)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1050)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1042)
System.err:     at com.tns.gen.android.support.design.widget.BaseTransientBottomBar_BaseCallback_vendor_98917_28_TNS_BaseCallback.onDismissed(BaseTransientBottomBar_BaseCallback_vendor_98917_28_TNS_BaseCallback.java:20)
System.err:     at android.support.design.widget.BaseTransientBottomBar.onViewHidden(BaseTransientBottomBar.java:687)
System.err:     at android.support.design.widget.BaseTransientBottomBar$10.onAnimationEnd(BaseTransientBottomBar.java:625)
System.err:     at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:552)
System.err:     at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1232)
System.err:     at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1474)
System.err:     at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
System.err:     at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
System.err:     at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1090)
System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:893)
System.err:     at android.view.Choreographer.doFrame(Choreographer.java:809)
System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
System.err:     at android.os.Handler.handleCallback(Handler.java:891)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
System.err:     at android.os.Looper.loop(Looper.java:207)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:7539)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
```

when i comment the `loading.hide()` the indicator will keep showing blocking the whole page but the app won't crash.

**Comment by NathanWalker** [comment]
@anaszgh are you using snackbar?

The stack you reported is not related to loading indicator however seems to come from (possibly) a snackbar? Possible your app is doing something else after the loading indicator closes?
<img width="680" alt="Screen Shot 2019-06-05 at 6 37 01 AM" src="https://user-images.githubusercontent.com/457187/58960687-8800b700-875c-11e9-9bd0-63dbf89f8b90.png">
<img width="729" alt="Screen Shot 2019-06-05 at 6 40 25 AM" src="https://user-images.githubusercontent.com/457187/58960844-d1510680-875c-11e9-8530-922ddd691037.png">
