### ISSUE TITLE
Cannot read property 'ViewCompat' of undefined

### ISSUE THREAD

**Issue by surdu** [NathanWalker/nativescript-loading-indicator#79]
### Which platform(s) does your issue occur on?
- Android 
- Android versions: 9
- emulator

### Please, provide the following version numbers that your issue occurs with:

```
$ tns info
✔ Getting NativeScript components versions information...
✔ Component nativescript has 6.1.1 version and is up to date.
✔ Component tns-core-modules has 6.1.1 version and is up to date.
✔ Component tns-android has 6.1.1 version and is up to date.
```

### Please, tell us how to recreate the issue in as much detail as possible. 
After upgrading to Nativescript 6, everytime I try to show the loading indicator I get the following error:

```
System.err: TypeError: Cannot read property 'ViewCompat' of undefined
System.err:
System.err: StackTrace:
System.err:     push.../node_modules/nativescript-loading-indicator/loading-indicator.js.LoadingIndicator._createPopOver(file:///node_modules/nativescript-loading-indicator/loading-indicator.js:73:0
)

System.err:     at push.../node_modules/nativescript-loading-indicator/loading-indicator.js.LoadingIndicator.show(file:///node_modules/nativescript-loading-indicator/loading-indicator.js:31:0)
System.err:     at attach(file:///app/misc/loader.js:9:0)
System.err:     at login(file:///app/views/login/login.page.js:27:0)
System.err:     at push.../node_modules/tns-core-modules/data/observable/observable.js.Observable.notify(file:///node_modules/tns-core-modules/data/observable/observable.js:110:0)
System.err:     at push.../node_modules/tns-core-modules/ui/text-field/text-field.js.TextField._onReturnPress(file:///node_modules/tns-core-modules/ui/text-field/text-field.js:19:0)
System.err:     at EditTextListenersImpl.onEditorAction(file:///node_modules/tns-core-modules/ui/editable-text-base/editable-text-base.js:92:0)
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1209)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1096)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1083)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1063)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1055)
System.err:     at com.tns.gen.java.lang.Object_vendor_35152_32_EditTextListenersImpl.onEditorAction(Object_vendor_35152_32_EditTextListenersImpl.java:56)
[...]
```

**Comment by EddyVerbruggen** [comment]
@surdu Please use https://github.com/nstudio/nativescript-loading-indicator instead (see the readme). Works for me perfectly fine with NativeScript 6.

Make sure you change your code as well; import from `@nstudio/nativescript-loading-indicator` instead of `nativescript-loading-indicator`.
